name: CI Build

on:
  push:

jobs:
      
  Android:
    runs-on: macos-latest
    steps:

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd Samples/RadarIO.Xamarin.Android.Sample
        msbuild
       
  iOS:
    runs-on: macos-11
    steps:

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore
        cd Samples/RadarIO.Xamarin.iOS.Sample
        msbuild